"""Fuzzer-grown exec seed scripts (minimized).

Generated by: python3 magni.py corpus promote --exec
Seeds: 0 promoted (hand scripts live in gen_exec_corpus.py EXEC_SEEDS)

Entries are (name, script) tuples appended by promotion; the counter is
scoped to this pool (independent from the parser corpus promoted_NNNN
sequence). Do not hand-edit. Regenerate scripts with
`python3 magni.py corpus generate --exec`.
"""

EXEC_PROMOTED = [
]
