"""Minimize the parser corpus: cmin → monster purge → rewrite promoted set.

Regenerates fuzz/corpus/promoted_seeds.py from the keep-set so the file
stays reproducible via `python3 magni.py corpus minimize`. Hand seeds in
gen_corpus.py are never touched. Aborts (leaving everything unchanged)
if tuple coverage would drop.
"""

import importlib.util
import re
import shutil
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

from . import config
from .build import ensure_cov_target
from .cmin import afl_cmin
from .corpus import corpus_generate, stage_corpus_into
from .showmap import showmap_tuples
from .util import die, log


def cmin_to_tmp() -> tuple[Path, Path, list[str]]:
    """Stage + afl-cmin into a temp dir. Returns (tmpdir, min_dir, kept)."""
    ensure_cov_target()
    tmpdir = Path(tempfile.mkdtemp(prefix="magni_minimize_"))
    staged = tmpdir / "staged"
    staged.mkdir()
    stage_corpus_into(config.CORPUS_DIR, staged)
    min_dir = tmpdir / "min"
    kept = afl_cmin(staged, min_dir)
    return tmpdir, min_dir, kept


def purge_monsters(min_dir: Path, kept: list[str], baseline: int) -> list[str]:
    """Drop oversized non-guard seeds; abort if coverage would drop."""
    # deep_* guard seeds are deliberate (MAX_PARSE_NESTING paths) and
    # always regenerated — never purge them.
    monsters = [n for n in kept
                if not n.startswith("deep_")
                and (min_dir / n).stat().st_size > config.MONSTER_SIZE_CAP]
    final = [n for n in kept if n not in monsters]
    log(f"  dropped {len(monsters)} files over {config.MONSTER_SIZE_CAP} bytes")
    if monsters:
        check_dir = Path(tempfile.mkdtemp(prefix="magni_verify_"))
        try:
            for n in final:
                shutil.copy2(min_dir / n, check_dir / n)
            kept_tuples = showmap_tuples(check_dir)
        finally:
            shutil.rmtree(check_dir, ignore_errors=True)
        if kept_tuples is None:
            die("verification showmap failed; aborting")
        lost = baseline - kept_tuples
        if lost > 0:
            die(f"monster purge would lose {lost} tuples; aborting "
                f"(tmin the monsters manually instead)")
        log(f"  verified: {kept_tuples}/{baseline} tuples, 0 loss")
    return final


def rewrite_promoted_seeds(final: list[str], kept_total: int, baseline: int) -> None:
    """Rewrite promoted_seeds.py from the keep-set (verified against disk)."""
    promoted_path = config.CORPUS_DIR / "promoted_seeds.py"
    kept_set = set(final)
    kept_entries = []
    for line in promoted_path.read_text(encoding="utf-8").split("\n"):
        m = re.match(r'^    \("([^"]+)",', line)
        if m:
            if m.group(1) in kept_set:
                kept_entries.append(line)
        else:
            # header/footer lines are regenerated below; skip them
            pass
    # Sanity: every kept promoted_* name must resolve to an entry
    disk_promoted = sorted(n for n in final if n.startswith("promoted_"))
    entry_names = sorted(
        re.match(r'^    \("([^"]+)",', ln).group(1) for ln in kept_entries)
    if disk_promoted != entry_names:
        log("keep-set/entry mismatch; aborting without changes")
        log(f"  on disk: {len(disk_promoted)}, in file: {len(entry_names)}")
        sys.exit(1)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    header = (f'"""Fuzzer-grown seed corpus (minimized).\n\n'
              f'Generated by: python3 magni.py corpus minimize\n'
              f'Last minimized: {stamp}\n'
              f'Seeds: {len(kept_entries)} promoted '
              f'({kept_total} files incl. hand seeds on disk)\n'
              f'Basis: afl-cmin + monster purge '
              f'(>{config.MONSTER_SIZE_CAP} bytes dropped)\n'
              f'Coverage verified: {baseline}/{baseline} tuples, 0 loss.\n\n'
              f'Do not hand-edit. To regenerate after a campaign, run\n'
              f'`python3 magni.py corpus promote` (appends new finds) then\n'
              f'`python3 magni.py corpus minimize` again.\n'
              f'"""\n\nPROMOTED_SEEDS = [\n')
    promoted_path.write_text(
        header + "".join(ln + "\n" for ln in kept_entries) + "]\n",
        encoding="utf-8")
    log(f"  wrote {len(kept_entries)} entries to {promoted_path}")


def regenerate_and_drop_stale() -> None:
    """Regenerate corpus from updated sources; remove minimized-away seeds."""
    log("Regenerating corpus from updated sources...")
    corpus_generate()
    # gen_corpus.py only removes files it knows about; drop stale seeds
    # left behind by the minimization (names no longer in SEEDS).
    sys.path.insert(0, str(config.CORPUS_DIR))
    try:
        spec = importlib.util.spec_from_file_location(
            "gen_corpus", str(config.GEN_CORPUS))
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
    finally:
        sys.path.remove(str(config.CORPUS_DIR))
    live = {name for name, _ in mod.SEEDS} | set(config.DEEP_GUARD_SEEDS) | {
        "gen_corpus.py", "promoted_seeds.py", "__pycache__",
    }
    stale = [f.name for f in config.CORPUS_DIR.iterdir()
             if f.is_file() and f.name not in live]
    for name in stale:
        (config.CORPUS_DIR / name).unlink()
    if stale:
        log(f"  removed {len(stale)} stale seeds")
    log("Done. Run `python3 magni.py corpus test` for the ASan gate.")


def corpus_minimize() -> None:
    tmpdir = None
    try:
        log("[1/4] Baseline tuple count...")
        baseline = showmap_tuples(config.CORPUS_DIR)
        if baseline is None:
            die("baseline showmap failed; aborting")
        log(f"  baseline: {baseline} tuples")

        log("[2/4] Minimizing with afl-cmin...")
        tmpdir, min_dir, kept = cmin_to_tmp()
        log(f"  cmin: {len(kept)} files kept")

        log("[3/4] Purging monsters...")
        final = purge_monsters(min_dir, kept, baseline)

        log("[4/4] Rewriting promoted_seeds.py...")
        rewrite_promoted_seeds(final, len(kept), baseline)
    finally:
        if tmpdir is not None:
            shutil.rmtree(tmpdir, ignore_errors=True)

    regenerate_and_drop_stale()
